export interface Refusal {
  id: string;
  date: string;
  status: 'detained' | 'refused' | 'released';
  importerName: string;
  importerSlug: string;
  originCountry: string;
  countryCode: string;
  productDescription: string;
  violationCode: string;
  violationSlug: string;
  port: string;
}

export interface Company {
  slug: string;
  name: string;
  verified: boolean;
  riskGrade: 'A' | 'B' | 'C' | 'F';
  logo: string;
  website: string;
  email: string;
  phone: string;
  address: string;
  coordinates: { lat: number; lng: number };
  country: string;
  about: string;
  totalRefusals: number;
  refusals: Refusal[];
  violationBreakdown: { name: string; value: number; color: string }[];
  industry: string;
  employees: string;
  founded: number;
}

export interface Violation {
  slug: string;
  code: string;
  title: string;
  definition: string;
  plainEnglish: string;
  topCompanies: { name: string; slug: string; count: number }[];
  recentCases: Refusal[];
}

export const violationCodes: Record<string, { code: string; title: string; slug: string }> = {
  '801a3': { code: 'Section 801(a)(3)', title: 'Adulteration', slug: '801a3' },
  '801a2': { code: 'Section 801(a)(2)', title: 'Misbranding', slug: '801a2' },
  '801a1': { code: 'Section 801(a)(1)', title: 'Unsafe Food Additives', slug: '801a1' },
  '402a4': { code: 'Section 402(a)(4)', title: 'Insanitary Conditions', slug: '402a4' },
  '403i': { code: 'Section 403(i)', title: 'Label Misrepresentation', slug: '403i' },
};

export const mockRefusals: Refusal[] = [
  {
    id: 'ref-001',
    date: '2024-01-15',
    status: 'refused',
    importerName: 'Oceanic Seafoods Ltd',
    importerSlug: 'oceanic-seafoods-ltd',
    originCountry: 'Vietnam',
    countryCode: 'VN',
    productDescription: 'Frozen Shrimp - Penaeus Vannamei',
    violationCode: 'Section 801(a)(3)',
    violationSlug: '801a3',
    port: 'Los Angeles',
  },
  {
    id: 'ref-002',
    date: '2024-01-14',
    status: 'detained',
    importerName: 'Golden Dragon Foods',
    importerSlug: 'golden-dragon-foods',
    originCountry: 'China',
    countryCode: 'CN',
    productDescription: 'Canned Mushrooms in Brine',
    violationCode: 'Section 402(a)(4)',
    violationSlug: '402a4',
    port: 'New York',
  },
  {
    id: 'ref-003',
    date: '2024-01-13',
    status: 'refused',
    importerName: 'Mediterranean Olive Co',
    importerSlug: 'mediterranean-olive-co',
    originCountry: 'Turkey',
    countryCode: 'TR',
    productDescription: 'Extra Virgin Olive Oil - 5L Containers',
    violationCode: 'Section 403(i)',
    violationSlug: '403i',
    port: 'Miami',
  },
  {
    id: 'ref-004',
    date: '2024-01-12',
    status: 'released',
    importerName: 'Andean Superfoods Inc',
    importerSlug: 'andean-superfoods-inc',
    originCountry: 'Peru',
    countryCode: 'PE',
    productDescription: 'Organic Quinoa - Bulk',
    violationCode: 'Section 801(a)(2)',
    violationSlug: '801a2',
    port: 'Houston',
  },
  {
    id: 'ref-005',
    date: '2024-01-11',
    status: 'refused',
    importerName: 'Spice Route Trading',
    importerSlug: 'spice-route-trading',
    originCountry: 'India',
    countryCode: 'IN',
    productDescription: 'Ground Turmeric Powder',
    violationCode: 'Section 801(a)(1)',
    violationSlug: '801a1',
    port: 'Seattle',
  },
  {
    id: 'ref-006',
    date: '2024-01-10',
    status: 'detained',
    importerName: 'Pacific Rim Imports',
    importerSlug: 'pacific-rim-imports',
    originCountry: 'Thailand',
    countryCode: 'TH',
    productDescription: 'Jasmine Rice - Premium Grade',
    violationCode: 'Section 801(a)(3)',
    violationSlug: '801a3',
    port: 'San Francisco',
  },
  {
    id: 'ref-007',
    date: '2024-01-09',
    status: 'refused',
    importerName: 'Euro Delicatessen GmbH',
    importerSlug: 'euro-delicatessen-gmbh',
    originCountry: 'Germany',
    countryCode: 'DE',
    productDescription: 'Aged Gouda Cheese',
    violationCode: 'Section 402(a)(4)',
    violationSlug: '402a4',
    port: 'Boston',
  },
  {
    id: 'ref-008',
    date: '2024-01-08',
    status: 'detained',
    importerName: 'Amazonia Natural Products',
    importerSlug: 'amazonia-natural-products',
    originCountry: 'Brazil',
    countryCode: 'BR',
    productDescription: 'Acai Berry Powder - Freeze Dried',
    violationCode: 'Section 801(a)(2)',
    violationSlug: '801a2',
    port: 'Newark',
  },
  {
    id: 'ref-009',
    date: '2024-01-07',
    status: 'refused',
    importerName: 'Nordic Fish Co',
    importerSlug: 'nordic-fish-co',
    originCountry: 'Norway',
    countryCode: 'NO',
    productDescription: 'Atlantic Salmon Fillets - Fresh',
    violationCode: 'Section 801(a)(3)',
    violationSlug: '801a3',
    port: 'Boston',
  },
  {
    id: 'ref-010',
    date: '2024-01-06',
    status: 'detained',
    importerName: 'Sakura Foods Japan',
    importerSlug: 'sakura-foods-japan',
    originCountry: 'Japan',
    countryCode: 'JP',
    productDescription: 'Instant Ramen Noodles - Assorted',
    violationCode: 'Section 403(i)',
    violationSlug: '403i',
    port: 'Los Angeles',
  },
  {
    id: 'ref-011',
    date: '2024-01-05',
    status: 'refused',
    importerName: 'Ceylon Tea Exports',
    importerSlug: 'ceylon-tea-exports',
    originCountry: 'Sri Lanka',
    countryCode: 'LK',
    productDescription: 'Ceylon Black Tea - Premium Grade',
    violationCode: 'Section 801(a)(1)',
    violationSlug: '801a1',
    port: 'New York',
  },
  {
    id: 'ref-012',
    date: '2024-01-04',
    status: 'refused',
    importerName: 'Aztec Avocado Farms',
    importerSlug: 'aztec-avocado-farms',
    originCountry: 'Mexico',
    countryCode: 'MX',
    productDescription: 'Fresh Hass Avocados',
    violationCode: 'Section 801(a)(3)',
    violationSlug: '801a3',
    port: 'San Diego',
  },
  {
    id: 'ref-013',
    date: '2024-01-03',
    status: 'detained',
    importerName: 'Kimchi King Corp',
    importerSlug: 'kimchi-king-corp',
    originCountry: 'South Korea',
    countryCode: 'KR',
    productDescription: 'Traditional Fermented Kimchi',
    violationCode: 'Section 402(a)(4)',
    violationSlug: '402a4',
    port: 'Seattle',
  },
  {
    id: 'ref-014',
    date: '2024-01-02',
    status: 'released',
    importerName: 'Italian Pasta Masters',
    importerSlug: 'italian-pasta-masters',
    originCountry: 'Italy',
    countryCode: 'IT',
    productDescription: 'Artisan Dried Pasta - Various Shapes',
    violationCode: 'Section 801(a)(2)',
    violationSlug: '801a2',
    port: 'Newark',
  },
  {
    id: 'ref-015',
    date: '2024-01-01',
    status: 'refused',
    importerName: 'Moroccan Spice Market',
    importerSlug: 'moroccan-spice-market',
    originCountry: 'Morocco',
    countryCode: 'MA',
    productDescription: 'Ras El Hanout Spice Blend',
    violationCode: 'Section 801(a)(1)',
    violationSlug: '801a1',
    port: 'Miami',
  },
  {
    id: 'ref-016',
    date: '2023-12-31',
    status: 'detained',
    importerName: 'Philippines Coconut Co',
    importerSlug: 'philippines-coconut-co',
    originCountry: 'Philippines',
    countryCode: 'PH',
    productDescription: 'Organic Coconut Oil - Virgin',
    violationCode: 'Section 403(i)',
    violationSlug: '403i',
    port: 'Long Beach',
  },
  {
    id: 'ref-017',
    date: '2023-12-30',
    status: 'refused',
    importerName: 'Australian Beef Exports',
    importerSlug: 'australian-beef-exports',
    originCountry: 'Australia',
    countryCode: 'AU',
    productDescription: 'Grass-Fed Beef - Prime Cuts',
    violationCode: 'Section 801(a)(3)',
    violationSlug: '801a3',
    port: 'Houston',
  },
  {
    id: 'ref-018',
    date: '2023-12-29',
    status: 'refused',
    importerName: 'Caribbean Rum Distillers',
    importerSlug: 'caribbean-rum-distillers',
    originCountry: 'Jamaica',
    countryCode: 'JM',
    productDescription: 'Aged Dark Rum - 12 Year',
    violationCode: 'Section 801(a)(2)',
    violationSlug: '801a2',
    port: 'Miami',
  },
];

export const mockCompanies: Record<string, Company> = {
  'oceanic-seafoods-ltd': {
    slug: 'oceanic-seafoods-ltd',
    name: 'Oceanic Seafoods Ltd',
    verified: true,
    riskGrade: 'C',
    logo: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=200&h=200&fit=crop',
    website: 'https://oceanicseafoods.example.com',
    email: 'contact@oceanicseafoods.example.com',
    phone: '+84 28 3823 4567',
    address: '123 Nguyen Hue Blvd, District 1, Ho Chi Minh City, Vietnam',
    coordinates: { lat: 10.7769, lng: 106.7009 },
    country: 'Vietnam',
    about: 'Oceanic Seafoods Ltd is a major Vietnamese seafood exporter specializing in frozen shrimp, fish, and shellfish products. Founded in 2005, the company operates three processing facilities along the Mekong Delta region.',
    totalRefusals: 12,
    refusals: [],
    violationBreakdown: [
      { name: 'Adulteration', value: 60, color: '#ef4444' },
      { name: 'Misbranding', value: 25, color: '#f97316' },
      { name: 'Contamination', value: 15, color: '#eab308' },
    ],
    industry: 'Seafood Processing',
    employees: '500-1000',
    founded: 2005,
  },
  'golden-dragon-foods': {
    slug: 'golden-dragon-foods',
    name: 'Golden Dragon Foods',
    verified: false,
    riskGrade: 'F',
    logo: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=200&h=200&fit=crop',
    website: 'https://goldendragonfoods.example.com',
    email: 'info@goldendragonfoods.example.com',
    phone: '+86 21 6888 9999',
    address: '456 Pudong Avenue, Shanghai, China 200120',
    coordinates: { lat: 31.2304, lng: 121.4737 },
    country: 'China',
    about: 'Golden Dragon Foods is a Chinese food manufacturer producing canned vegetables, mushrooms, and preserved foods. The company has been operating since 1998 and exports to over 30 countries worldwide.',
    totalRefusals: 28,
    refusals: [],
    violationBreakdown: [
      { name: 'Insanitary Conditions', value: 45, color: '#ef4444' },
      { name: 'Contamination', value: 35, color: '#f97316' },
      { name: 'Label Issues', value: 20, color: '#eab308' },
    ],
    industry: 'Canned Foods',
    employees: '1000-5000',
    founded: 1998,
  },
  'mediterranean-olive-co': {
    slug: 'mediterranean-olive-co',
    name: 'Mediterranean Olive Co',
    verified: true,
    riskGrade: 'B',
    logo: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=200&h=200&fit=crop',
    website: 'https://medolive.example.com',
    email: 'export@medolive.example.com',
    phone: '+90 232 456 7890',
    address: '789 Aegean Coast Road, Izmir, Turkey 35000',
    coordinates: { lat: 38.4237, lng: 27.1428 },
    country: 'Turkey',
    about: 'Mediterranean Olive Co produces premium olive oils and table olives from the Aegean region of Turkey. Family-owned since 1952, they maintain traditional cold-press extraction methods.',
    totalRefusals: 3,
    refusals: [],
    violationBreakdown: [
      { name: 'Label Misrepresentation', value: 100, color: '#eab308' },
    ],
    industry: 'Olive Oil Production',
    employees: '100-250',
    founded: 1952,
  },
  'andean-superfoods-inc': {
    slug: 'andean-superfoods-inc',
    name: 'Andean Superfoods Inc',
    verified: true,
    riskGrade: 'A',
    logo: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=200&h=200&fit=crop',
    website: 'https://andean-superfoods.example.com',
    email: 'sales@andean-superfoods.example.com',
    phone: '+51 1 555 7890',
    address: '321 Av. La Marina, Lima, Peru',
    coordinates: { lat: -12.0464, lng: -77.0428 },
    country: 'Peru',
    about: 'Andean Superfoods Inc specializes in organic quinoa, maca, and other Peruvian superfoods. They work directly with indigenous farming cooperatives in the Andes mountains.',
    totalRefusals: 2,
    refusals: [],
    violationBreakdown: [
      { name: 'Misbranding', value: 100, color: '#f97316' },
    ],
    industry: 'Organic Foods',
    employees: '50-100',
    founded: 2010,
  },
  'spice-route-trading': {
    slug: 'spice-route-trading',
    name: 'Spice Route Trading',
    verified: true,
    riskGrade: 'C',
    logo: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=200&h=200&fit=crop',
    website: 'https://spiceroute.example.com',
    email: 'orders@spiceroute.example.com',
    phone: '+91 22 4455 6677',
    address: '88 Spice Market Road, Mumbai, India 400001',
    coordinates: { lat: 19.0760, lng: 72.8777 },
    country: 'India',
    about: 'Spice Route Trading is one of India\'s largest spice exporters, offering turmeric, cumin, cardamom, and custom spice blends. Established in 1985, they source from farms across Kerala and Tamil Nadu.',
    totalRefusals: 9,
    refusals: [],
    violationBreakdown: [
      { name: 'Unsafe Additives', value: 55, color: '#ef4444' },
      { name: 'Contamination', value: 45, color: '#f97316' },
    ],
    industry: 'Spices & Seasonings',
    employees: '250-500',
    founded: 1985,
  },
  'pacific-rim-imports': {
    slug: 'pacific-rim-imports',
    name: 'Pacific Rim Imports',
    verified: false,
    riskGrade: 'C',
    logo: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=200&h=200&fit=crop',
    website: 'https://pacificrim-imports.example.com',
    email: 'contact@pacificrim-imports.example.com',
    phone: '+66 2 555 8899',
    address: '456 Silom Road, Bangkok, Thailand 10500',
    coordinates: { lat: 13.7563, lng: 100.5018 },
    country: 'Thailand',
    about: 'Pacific Rim Imports exports Thai rice, coconut products, and tropical fruits. The company has partnerships with over 200 rice farms in the Chao Phraya Basin.',
    totalRefusals: 8,
    refusals: [],
    violationBreakdown: [
      { name: 'Adulteration', value: 70, color: '#ef4444' },
      { name: 'Misbranding', value: 30, color: '#f97316' },
    ],
    industry: 'Grains & Rice',
    employees: '100-250',
    founded: 2001,
  },
  'euro-delicatessen-gmbh': {
    slug: 'euro-delicatessen-gmbh',
    name: 'Euro Delicatessen GmbH',
    verified: true,
    riskGrade: 'B',
    logo: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=200&h=200&fit=crop',
    website: 'https://euro-deli.example.com',
    email: 'export@euro-deli.example.com',
    phone: '+49 30 1234 5678',
    address: '123 Kurfürstendamm, Berlin, Germany 10719',
    coordinates: { lat: 52.5200, lng: 13.4050 },
    country: 'Germany',
    about: 'Euro Delicatessen GmbH specializes in European gourmet cheeses, cured meats, and specialty foods. They curate products from artisan producers across France, Italy, and Germany.',
    totalRefusals: 6,
    refusals: [],
    violationBreakdown: [
      { name: 'Insanitary Conditions', value: 60, color: '#ef4444' },
      { name: 'Label Issues', value: 40, color: '#eab308' },
    ],
    industry: 'Gourmet Foods',
    employees: '50-100',
    founded: 1995,
  },
  'amazonia-natural-products': {
    slug: 'amazonia-natural-products',
    name: 'Amazonia Natural Products',
    verified: true,
    riskGrade: 'B',
    logo: 'https://images.unsplash.com/photo-1546548970-71785318a17b?w=200&h=200&fit=crop',
    website: 'https://amazonia-natural.example.com',
    email: 'sales@amazonia-natural.example.com',
    phone: '+55 11 3456 7890',
    address: '789 Av. Paulista, São Paulo, Brazil 01310',
    coordinates: { lat: -23.5505, lng: -46.6333 },
    country: 'Brazil',
    about: 'Amazonia Natural Products harvests açaí, Brazil nuts, and other superfoods sustainably from the Amazon rainforest. They employ over 500 local harvesters and operate freeze-drying facilities in Belém.',
    totalRefusals: 5,
    refusals: [],
    violationBreakdown: [
      { name: 'Misbranding', value: 65, color: '#f97316' },
      { name: 'Contamination', value: 35, color: '#ef4444' },
    ],
    industry: 'Superfoods',
    employees: '500-1000',
    founded: 2008,
  },
  'nordic-fish-co': {
    slug: 'nordic-fish-co',
    name: 'Nordic Fish Co',
    verified: true,
    riskGrade: 'A',
    logo: 'https://images.unsplash.com/photo-1544943910-4c1dc44aab44?w=200&h=200&fit=crop',
    website: 'https://nordicfish.example.com',
    email: 'export@nordicfish.example.com',
    phone: '+47 22 33 44 55',
    address: '100 Harbor Street, Bergen, Norway 5003',
    coordinates: { lat: 60.3913, lng: 5.3221 },
    country: 'Norway',
    about: 'Nordic Fish Co is a premium Norwegian seafood exporter specializing in Atlantic salmon and cod. They operate sustainable fish farms along the fjords with strict quality controls.',
    totalRefusals: 2,
    refusals: [],
    violationBreakdown: [
      { name: 'Adulteration', value: 100, color: '#ef4444' },
    ],
    industry: 'Seafood',
    employees: '250-500',
    founded: 1990,
  },
  'sakura-foods-japan': {
    slug: 'sakura-foods-japan',
    name: 'Sakura Foods Japan',
    verified: true,
    riskGrade: 'A',
    logo: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=200&h=200&fit=crop',
    website: 'https://sakura-foods.example.jp',
    email: 'intl@sakura-foods.example.jp',
    phone: '+81 3 5555 6666',
    address: '2-1-1 Nihonbashi, Chuo-ku, Tokyo, Japan 103-0027',
    coordinates: { lat: 35.6762, lng: 139.7680 },
    country: 'Japan',
    about: 'Sakura Foods Japan produces authentic Japanese food products including instant ramen, soy sauce, and miso. Family-owned for three generations, they combine traditional recipes with modern food safety standards.',
    totalRefusals: 1,
    refusals: [],
    violationBreakdown: [
      { name: 'Label Issues', value: 100, color: '#eab308' },
    ],
    industry: 'Japanese Foods',
    employees: '1000-5000',
    founded: 1962,
  },
  'ceylon-tea-exports': {
    slug: 'ceylon-tea-exports',
    name: 'Ceylon Tea Exports',
    verified: true,
    riskGrade: 'B',
    logo: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=200&h=200&fit=crop',
    website: 'https://ceylontea.example.com',
    email: 'orders@ceylontea.example.com',
    phone: '+94 11 234 5678',
    address: '45 Tea Garden Road, Colombo, Sri Lanka 00100',
    coordinates: { lat: 6.9271, lng: 79.8612 },
    country: 'Sri Lanka',
    about: 'Ceylon Tea Exports is a premier exporter of Sri Lankan black and green teas. They work with over 150 tea estates in the central highlands, known for producing some of the world\'s finest teas.',
    totalRefusals: 4,
    refusals: [],
    violationBreakdown: [
      { name: 'Unsafe Additives', value: 75, color: '#ef4444' },
      { name: 'Contamination', value: 25, color: '#f97316' },
    ],
    industry: 'Tea & Beverages',
    employees: '100-250',
    founded: 1978,
  },
  'aztec-avocado-farms': {
    slug: 'aztec-avocado-farms',
    name: 'Aztec Avocado Farms',
    verified: false,
    riskGrade: 'C',
    logo: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=200&h=200&fit=crop',
    website: 'https://aztec-avocado.example.com',
    email: 'sales@aztec-avocado.example.com',
    phone: '+52 443 123 4567',
    address: '789 Carretera Uruapan, Michoacán, Mexico 60000',
    coordinates: { lat: 19.4285, lng: -99.1277 },
    country: 'Mexico',
    about: 'Aztec Avocado Farms is one of Mexico\'s largest avocado exporters, operating orchards across Michoacán state. They supply fresh Hass avocados to major retailers throughout North America.',
    totalRefusals: 11,
    refusals: [],
    violationBreakdown: [
      { name: 'Adulteration', value: 55, color: '#ef4444' },
      { name: 'Contamination', value: 30, color: '#f97316' },
      { name: 'Misbranding', value: 15, color: '#eab308' },
    ],
    industry: 'Fresh Produce',
    employees: '500-1000',
    founded: 2003,
  },
  'kimchi-king-corp': {
    slug: 'kimchi-king-corp',
    name: 'Kimchi King Corp',
    verified: true,
    riskGrade: 'B',
    logo: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=200&h=200&fit=crop',
    website: 'https://kimchiking.example.kr',
    email: 'export@kimchiking.example.kr',
    phone: '+82 2 1234 5678',
    address: '456 Gangnam-daero, Seoul, South Korea 06000',
    coordinates: { lat: 37.5665, lng: 126.9780 },
    country: 'South Korea',
    about: 'Kimchi King Corp produces traditional Korean fermented foods including kimchi, gochujang, and doenjang. They use time-honored fermentation methods passed down through generations.',
    totalRefusals: 5,
    refusals: [],
    violationBreakdown: [
      { name: 'Insanitary Conditions', value: 60, color: '#ef4444' },
      { name: 'Label Issues', value: 40, color: '#eab308' },
    ],
    industry: 'Fermented Foods',
    employees: '250-500',
    founded: 1988,
  },
  'italian-pasta-masters': {
    slug: 'italian-pasta-masters',
    name: 'Italian Pasta Masters',
    verified: true,
    riskGrade: 'A',
    logo: 'https://images.unsplash.com/photo-1551462147-37885acc36f1?w=200&h=200&fit=crop',
    website: 'https://pasta-masters.example.it',
    email: 'export@pasta-masters.example.it',
    phone: '+39 06 1234 5678',
    address: '123 Via del Corso, Rome, Italy 00186',
    coordinates: { lat: 41.9028, lng: 12.4964 },
    country: 'Italy',
    about: 'Italian Pasta Masters crafts premium dried pasta using traditional bronze die methods and slow drying. They source durum wheat from Italian farms and maintain century-old recipes.',
    totalRefusals: 1,
    refusals: [],
    violationBreakdown: [
      { name: 'Misbranding', value: 100, color: '#f97316' },
    ],
    industry: 'Pasta & Grains',
    employees: '100-250',
    founded: 1925,
  },
  'moroccan-spice-market': {
    slug: 'moroccan-spice-market',
    name: 'Moroccan Spice Market',
    verified: false,
    riskGrade: 'C',
    logo: 'https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=200&h=200&fit=crop',
    website: 'https://moroccan-spices.example.com',
    email: 'orders@moroccan-spices.example.com',
    phone: '+212 522 123 456',
    address: '789 Rue des Épices, Casablanca, Morocco 20000',
    coordinates: { lat: 33.5731, lng: -7.5898 },
    country: 'Morocco',
    about: 'Moroccan Spice Market exports traditional Moroccan spice blends, preserved lemons, and argan oil. They source from small producers throughout Morocco and blend spices using traditional methods.',
    totalRefusals: 7,
    refusals: [],
    violationBreakdown: [
      { name: 'Unsafe Additives', value: 50, color: '#ef4444' },
      { name: 'Contamination', value: 35, color: '#f97316' },
      { name: 'Label Issues', value: 15, color: '#eab308' },
    ],
    industry: 'Spices & Seasonings',
    employees: '50-100',
    founded: 1997,
  },
  'philippines-coconut-co': {
    slug: 'philippines-coconut-co',
    name: 'Philippines Coconut Co',
    verified: true,
    riskGrade: 'B',
    logo: 'https://images.unsplash.com/photo-1550411294-098be0fb39e4?w=200&h=200&fit=crop',
    website: 'https://ph-coconut.example.com',
    email: 'sales@ph-coconut.example.com',
    phone: '+63 2 8888 9999',
    address: '321 Makati Avenue, Manila, Philippines 1200',
    coordinates: { lat: 14.5995, lng: 120.9842 },
    country: 'Philippines',
    about: 'Philippines Coconut Co produces organic virgin coconut oil, coconut flour, and coconut sugar. They work with smallholder farmers across Mindanao and operate modern processing facilities.',
    totalRefusals: 4,
    refusals: [],
    violationBreakdown: [
      { name: 'Label Issues', value: 70, color: '#eab308' },
      { name: 'Misbranding', value: 30, color: '#f97316' },
    ],
    industry: 'Coconut Products',
    employees: '250-500',
    founded: 2006,
  },
  'australian-beef-exports': {
    slug: 'australian-beef-exports',
    name: 'Australian Beef Exports',
    verified: true,
    riskGrade: 'A',
    logo: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=200&h=200&fit=crop',
    website: 'https://ausbeef.example.com',
    email: 'trade@ausbeef.example.com',
    phone: '+61 2 9876 5432',
    address: '456 Stockyard Drive, Sydney, Australia 2000',
    coordinates: { lat: -33.8688, lng: 151.2093 },
    country: 'Australia',
    about: 'Australian Beef Exports supplies premium grass-fed and grain-fed beef from certified Australian farms. They maintain strict animal welfare and food safety certifications.',
    totalRefusals: 2,
    refusals: [],
    violationBreakdown: [
      { name: 'Adulteration', value: 100, color: '#ef4444' },
    ],
    industry: 'Meat & Poultry',
    employees: '100-250',
    founded: 1985,
  },
  'caribbean-rum-distillers': {
    slug: 'caribbean-rum-distillers',
    name: 'Caribbean Rum Distillers',
    verified: true,
    riskGrade: 'B',
    logo: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=200&h=200&fit=crop',
    website: 'https://caribbean-rum.example.com',
    email: 'export@caribbean-rum.example.com',
    phone: '+1 876 555 1234',
    address: '789 Rum Lane, Kingston, Jamaica',
    coordinates: { lat: 18.0179, lng: -76.8099 },
    country: 'Jamaica',
    about: 'Caribbean Rum Distillers produces aged premium rums using traditional pot still methods. Their master blenders create smooth, complex spirits aged in oak barrels for up to 25 years.',
    totalRefusals: 3,
    refusals: [],
    violationBreakdown: [
      { name: 'Misbranding', value: 65, color: '#f97316' },
      { name: 'Label Issues', value: 35, color: '#eab308' },
    ],
    industry: 'Spirits & Beverages',
    employees: '100-250',
    founded: 1945,
  },
};

Object.keys(mockCompanies).forEach(slug => {
  mockCompanies[slug].refusals = mockRefusals.filter(r => r.importerSlug === slug);
});

export const mockViolations: Record<string, Violation> = {
  '801a3': {
    slug: '801a3',
    code: 'Section 801(a)(3)',
    title: 'Adulteration',
    definition: 'Under Section 801(a)(3) of the Federal Food, Drug, and Cosmetic Act, an article of food, drug, device, or cosmetic may be refused admission if it appears that such article is adulterated.',
    plainEnglish: 'This means the product has been contaminated, contains unsafe additives, or was produced under unsanitary conditions that could make it harmful to consumers. Common issues include pesticide residues, bacterial contamination, or undeclared ingredients.',
    topCompanies: [
      { name: 'Golden Dragon Foods', slug: 'golden-dragon-foods', count: 28 },
      { name: 'Oceanic Seafoods Ltd', slug: 'oceanic-seafoods-ltd', count: 12 },
      { name: 'Aztec Avocado Farms', slug: 'aztec-avocado-farms', count: 11 },
      { name: 'Spice Route Trading', slug: 'spice-route-trading', count: 9 },
      { name: 'Pacific Rim Imports', slug: 'pacific-rim-imports', count: 8 },
    ],
    recentCases: mockRefusals.filter(r => r.violationSlug === '801a3'),
  },
  '801a2': {
    slug: '801a2',
    code: 'Section 801(a)(2)',
    title: 'Misbranding',
    definition: 'Under Section 801(a)(2), an article may be refused if it appears to be misbranded within the meaning of the Act.',
    plainEnglish: 'The product\'s labeling is false or misleading, missing required information, or doesn\'t meet FDA labeling requirements. This includes incorrect ingredient lists, missing allergen warnings, or false health claims.',
    topCompanies: [
      { name: 'Amazonia Natural Products', slug: 'amazonia-natural-products', count: 5 },
      { name: 'Caribbean Rum Distillers', slug: 'caribbean-rum-distillers', count: 3 },
      { name: 'Andean Superfoods Inc', slug: 'andean-superfoods-inc', count: 2 },
    ],
    recentCases: mockRefusals.filter(r => r.violationSlug === '801a2'),
  },
  '801a1': {
    slug: '801a1',
    code: 'Section 801(a)(1)',
    title: 'Unsafe Food Additives',
    definition: 'Section 801(a)(1) prohibits entry of articles that contain unsafe food additives, color additives, or new drugs that are not approved.',
    plainEnglish: 'The product contains additives, colors, or substances that haven\'t been approved by the FDA or are used at levels that exceed safety limits. This could include artificial colors banned in the US or preservatives at unsafe concentrations.',
    topCompanies: [
      { name: 'Spice Route Trading', slug: 'spice-route-trading', count: 9 },
      { name: 'Moroccan Spice Market', slug: 'moroccan-spice-market', count: 7 },
      { name: 'Ceylon Tea Exports', slug: 'ceylon-tea-exports', count: 4 },
    ],
    recentCases: mockRefusals.filter(r => r.violationSlug === '801a1'),
  },
  '402a4': {
    slug: '402a4',
    code: 'Section 402(a)(4)',
    title: 'Insanitary Conditions',
    definition: 'A food shall be deemed adulterated if it has been prepared, packed, or held under insanitary conditions whereby it may have become contaminated with filth, or whereby it may have been rendered injurious to health.',
    plainEnglish: 'The product was made or stored in dirty or unsafe conditions. This could mean the factory had pest problems, workers didn\'t follow hygiene rules, or equipment wasn\'t properly cleaned.',
    topCompanies: [
      { name: 'Golden Dragon Foods', slug: 'golden-dragon-foods', count: 15 },
      { name: 'Euro Delicatessen GmbH', slug: 'euro-delicatessen-gmbh', count: 6 },
      { name: 'Kimchi King Corp', slug: 'kimchi-king-corp', count: 5 },
    ],
    recentCases: mockRefusals.filter(r => r.violationSlug === '402a4'),
  },
  '403i': {
    slug: '403i',
    code: 'Section 403(i)',
    title: 'Label Misrepresentation',
    definition: 'A food shall be deemed misbranded if its container is so made, formed, or filled as to be misleading.',
    plainEnglish: 'The product label doesn\'t match what\'s actually inside. This includes false claims about ingredients, origin, or quality. For example, labeling regular olive oil as "extra virgin" when it isn\'t.',
    topCompanies: [
      { name: 'Philippines Coconut Co', slug: 'philippines-coconut-co', count: 4 },
      { name: 'Mediterranean Olive Co', slug: 'mediterranean-olive-co', count: 3 },
      { name: 'Sakura Foods Japan', slug: 'sakura-foods-japan', count: 1 },
    ],
    recentCases: mockRefusals.filter(r => r.violationSlug === '403i'),
  },
};

export const countryHotspots = [
  { country: 'China', code: 'CN', count: 245, coordinates: [104.1954, 35.8617] as [number, number] },
  { country: 'India', code: 'IN', count: 187, coordinates: [78.9629, 20.5937] as [number, number] },
  { country: 'Vietnam', code: 'VN', count: 156, coordinates: [108.2772, 14.0583] as [number, number] },
  { country: 'Mexico', code: 'MX', count: 134, coordinates: [-102.5528, 23.6345] as [number, number] },
  { country: 'Thailand', code: 'TH', count: 98, coordinates: [100.9925, 15.8700] as [number, number] },
  { country: 'Brazil', code: 'BR', count: 76, coordinates: [-51.9253, -14.2350] as [number, number] },
  { country: 'Turkey', code: 'TR', count: 54, coordinates: [35.2433, 38.9637] as [number, number] },
  { country: 'Indonesia', code: 'ID', count: 43, coordinates: [113.9213, -0.7893] as [number, number] },
  { country: 'Philippines', code: 'PH', count: 38, coordinates: [121.7740, 12.8797] as [number, number] },
  { country: 'Peru', code: 'PE', count: 32, coordinates: [-75.0152, -9.1900] as [number, number] },
  { country: 'Morocco', code: 'MA', count: 28, coordinates: [-7.0926, 31.7917] as [number, number] },
  { country: 'South Korea', code: 'KR', count: 25, coordinates: [127.7669, 35.9078] as [number, number] },
];

export const ports = [
  'Los Angeles', 'New York', 'Miami', 'Houston', 'Seattle', 
  'San Francisco', 'Boston', 'Newark', 'Long Beach', 'San Diego',
  'Chicago', 'Atlanta', 'Dallas', 'Detroit', 'Philadelphia'
];
